---
title: "01_load_clean"
format: html
editor_options: 
  chunk_output_type: console
---

## Load Libraries

```{r}
#| warning: false
#| message: false

library(tidyverse)
library(here)
```

## Load Data

Handling of different types of NAs

```{r}
mr_bact_data <- read.csv(here("data/_raw/Bacteria_dataset_Multiresictance.csv"),
  na.strings = c("", " ", "NA", "?", "missing", "unknown", "None", "error"))
```

## Data Cleaning

**Analyze for duplicates and select relevant columns**

```{r}
# Identify any duplicates to remove 
dup_IDs <- mr_bact_data |>
  add_count(ID, name = "n") |>
  filter(n > 1)

#No duplicates in the dataset
dup_IDs

mr_bact_data <- mr_bact_data |> 
  select(-ID, -Name, -Email, -Address, -Collection_Date, -Notes) 
```

**Separate data into individual columns and remove NA rows**

```{r}
#| warning: false

mr_bact_data <- mr_bact_data |> 
  separate(age.gender,
           into = c("Age", "Gender"),
           sep = "/") |> 
  separate(Souches, 
           into = c("ID", "Species"),
           sep = " ",
           extra = "merge") |>  # only separate based on the first space 
  select(-ID) |> 
  filter(!(is.na(Species))) 
```

**Identify typos and inconsistencies in naming**

```{r}
get_unique_counts <- function(data, column_name) {
  data |>
    count(.data[[column_name]])
}

res <- map(colnames(mr_bact_data), 
           ~ get_unique_counts(mr_bact_data, .x))

res
```

**Rename accordingly**

```{r}
mr_bact_data <- mr_bact_data |> 
  mutate(Species = case_when(
  Species %in% c("E.cli", "E.coi", "E.coli", "E. coli") ~ "Escherichia coli",
  Species %in% c("Klbsiella pneumoniae", "Klebsie.lla pneumoniae") ~ "Klebsiella pneumoniae",
  Species %in% c("Enter.bacteria spp.", "Enteobacteria spp.") ~ "Enterobacteria spp.",
  Species %in% c("Prot.eus mirabilis", "Protus mirabilis", "Proeus mirabilis") ~ "Proteus mirabilis",
  TRUE ~ Species # Keep everything else unchanged 
))

mr_bact_data <- mr_bact_data |>
  mutate(
    Diabetes = case_when(
      Diabetes == "True" ~ "Yes",
      TRUE ~ Diabetes
    ),
    Hypertension = case_when(
      Hypertension == "True" ~ "Yes",
      TRUE ~ Hypertension
    )
  )

fix_resistance <- function(x) {
  case_when(
    x == "r" ~ "R",
    x == "s" ~ "S",
    x %in% c("i", "Intermediate") ~ "I",
    TRUE ~ x
  )
}

mr_bact_data <- mr_bact_data |>
  mutate(across(colnames(mr_bact_data)[c(8:ncol(mr_bact_data))], 
                fix_resistance))
```

**Save the cleaned data**

```{r}
write.csv(mr_bact_data, 
          here("data/cleaned_bacteria_data.csv"), 
          row.names = FALSE)

```
