---
title: "01_load"
author: "Edene Levine (s240875), Molly Hong-Minh (s242955), Pablo Fernandez (s243357), Vinit Nilesh Vasa (s242582)"
format: 
   html:
    embed-resources: true
editor: visual
---

## Uploading Data

### Data

Data for this project comes from: <https://www.kaggle.com/datasets/adilimadeddinehosni/multi-resistance-antibiotic-susceptibility/data>

### Load Libraries

```{r}
#| warning: false
#| message: false

library("tidyverse")
library("here")
library("RKaggle")
```

### Create Data Folder

```{r}
data_dir <- here("data")
raw_data_dir <- here("data", "_raw")
results_dir <- here("results")

if( !dir.exists(data_dir) ){
  dir.create(path = data_dir)
}

if( !dir.exists(raw_data_dir) ){
  dir.create(path = raw_data_dir, recursive = TRUE)
}

if( !dir.exists(results_dir) ){
  dir.create(path = results_dir)
}
```

### Upload Data

```{r}
#| warning: false
#| message: false

raw_file <- here("data", "_raw", "Bacteria_dataset_Multiresistance.csv")

# Download data from kaggle and save if not already present
if (!file.exists(raw_file)) {
  df <- RKaggle::get_dataset("adilimadeddinehosni/multi-resistance-antibiotic-susceptibility")
  write_csv(df, raw_file)
}
```
