---
title: "02_clean"
author: "Eden Levine (s240875), Molly Hong-Minh (s242955), Pablo Fernandez (s243357), Vinit Nilesh Vasa (s242582)"
format: 
   html:
    embed-resources: true
editor: visual
---

## Load Libraries

```{r}
#| warning: false
#| message: false

library(tidyverse)
library(here)
```

## Load Functions

```{r}
source(here("R/99_proj_func.R"))
```

## Load Data

Handling of different types of NAs

```{r}
mdr_data <- read.csv(here("data/_raw/Bacteria_dataset_Multiresistance.csv"),
  na.strings = c("", " ", "NA", "?", "missing", "unknown", "None", "error"))
```

## Data Cleaning

**Analyze for duplicates and select relevant columns**

```{r}
# Identify any duplicates to remove 
dup_IDs <- mdr_data |>
  add_count(ID, name = "n") |>
  filter(n > 1)

#No duplicates in the dataset
dup_IDs

mdr_data <- mdr_data |> 
  select(-ID, -Name, -Email, -Address, -Collection_Date, -Notes) 
```

**Separate data into individual columns and remove NA rows**

```{r}
#| warning: false

mdr_data <- mdr_data |> 
  separate(age.gender,
           into = c("Age", "Gender"),
           sep = "/") |> 
  separate(Souches, 
           into = c("ID", "Species"),
           sep = " ",
           extra = "merge") |>  # only separate based on the first space 
  select(-ID) |> 
  filter(!(is.na(Species))) 
```

**Identify typos and inconsistencies in naming**

```{r}
#get_unique_counts is a function in 99_proj_func.R
res <- map(colnames(mdr_data), 
           ~ get_unique_counts(mdr_data, .x))

res
```

**Rename accordingly**

```{r}
mdr_data <- mdr_data |> 
  mutate(Species = case_when(
  Species %in% c("E.cli", "E.coi", "E.coli", "E. coli") ~ "Escherichia coli",
  Species %in% c("Klbsiella pneumoniae", "Klebsie.lla pneumoniae") ~ "Klebsiella pneumoniae",
  Species %in% c("Enter.bacteria spp.", "Enteobacteria spp.") ~ "Enterobacteria spp.",
  Species %in% c("Prot.eus mirabilis", "Protus mirabilis", "Proeus mirabilis") ~ "Proteus mirabilis",
  TRUE ~ Species # Keep everything else unchanged 
))

mdr_data <- mdr_data |>
  mutate(
    Diabetes = case_when(
      Diabetes == "True" ~ "Yes",
      TRUE ~ Diabetes
    ),
    Hypertension = case_when(
      Hypertension == "True" ~ "Yes",
      TRUE ~ Hypertension
    )
  )

#fix_resistance is a function in 99_proj_func.R
mdr_data <- mdr_data |>
  mutate(across(colnames(mdr_data)[c(8:ncol(mdr_data))], fix_resistance))
```

**Save the cleaned data**

```{r}
write.csv(mdr_data, here("data/cleaned_bacteria_data.csv"), row.names = FALSE)

```
