---
title: "06_Infection Linear Model"
author: "Edene Levine (s240875), Molly Hong-Minh (s242955), Pablo Fernandez (s243357), Vinit Nilesh Vasa (s242582)"
format: 
   html:
    embed-resources: true
editor: visual
---

### Load libraries

```{r}
#| warning: false
#| message: false

library("tidyverse") 
library("dplyr")
library("here")
library("broom")
library("ggrepel")
```

### Load data

```{r}

infect_db <- read_csv(here("data/03_dat_aug_wide.csv"),
                      show_col_types = FALSE)
```

#### First model: Is infection frequency correlated to patient details?

```{r}
model1 <- infect_db |> 
  lm(Infection_Freq ~ Age + Diabetes + Hypertension + Hospital_before,
  data = _
)
summary(model1)
```

#### Second model: Is infection frequency correlated with the species?

```{r}
model2 <- infect_db |> 
  lm(Infection_Freq ~ Species,
  data = _
)
summary(model2)
```

#### Third model: Is infection frequency correlated with multiple drug resistance?

```{r}
model3 <- infect_db |> 
  lm(Infection_Freq ~ MDR,
  data = _
)
summary(model3)
```

#### 

```{r}
model_full <- infect_db |> 
  lm(Infection_Freq ~ Species + MDR + Age + Gender + 
       Diabetes + Hypertension + Hospital_before,
  data = _
)
summary(model_full)
```

```{r}
tidy_lm <- tidy(model_full, 
     conf.int = TRUE,
     conf.level = 0.95) |> 
  mutate(term = str_replace(term, "Species", "")) |> 
  mutate(term = str_replace(term, "Yes", "")) |> 
  mutate(term = str_replace(term, "GenderM", "Gender_M")) |> 
  mutate(term = str_replace(term, "Freq1", "Freq_1")) |>
  mutate(term = str_replace(term, "Freq2", "Freq_2")) |>
  mutate(term = str_replace(term, "Freq3", "Freq_3")) |> 
  mutate(sig = factor(p.value < 0.05))
  

tidy_lm
```

```{r}
#| warning: false
#| message: false
infect_plot1 <- tidy_lm |>
  filter(term != "(Intercept)") |>
  mutate(term = fct_reorder(term, estimate)) |>
  ggplot(aes(y = term, x = estimate)) +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.2) +
  geom_point() +
  geom_vline(xintercept = 0, linetype = "dashed") +
  labs(x = "Estimates (95% CIs)",
       y = "",
       title = "Factors associated with infection frequency") +
  theme_minimal()

ggsave(filename = "06_inf_freq_forest.png", plot = infect_plot1, path = here("results/images"), dpi = 300)
infect_plot1
```

```{r}
tidy_lm <- tidy_lm |> 
  mutate(q.value = p.adjust(p.value),
         is_significant = case_when(q.value <= 0.05 ~ "yes",
                                    q.value > 0.05 ~ "no"))
```

```{r}
#| warning: false
#| message: false
pl <- tidy_lm |>
  filter(term != "(Intercept)") |>
  ggplot(aes(x = estimate,
             y = -log10(p.value),
             colour = sig,
             label = term)) +
  geom_point(size = 1,
             alpha = 0.5) +
  geom_text_repel(size = 2.5,
                  max.overlaps = 20) +
  geom_hline(yintercept = -log10(0.05), linetype = "dotted") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_minimal(base_size = 16) +
  theme(
    plot.title = element_text(hjust = 1),
    plot.subtitle = element_text(hjust = 1),
    legend.position = "none") +
    labs(
    x = "Estimates",
    y = "-log10(p)",
    title = "Factors associated with infection frequency",
    subtitle = "Factors highlighted in turquoise are significant")

ggsave(filename = "06_inf_freq_volcano.png", plot = pl, path = here("results/images"), dpi = 300)
pl
```
