---
title: "Infection Linear Model"
format: html
editor: visual
---

### Load libraries

```{r}
library("tidyverse") 
library("dplyr")
library("here")
library("broom")
library("ggrepel")
```

### Load data

```{r}
infect_db <- read_csv(here("data/cleaned_bacteria_data.csv"))
```

```{r}
infect_db
```

```{r}
count_resistance <- function(x) {
  case_when(
    x == "R" ~ 1,
    x == "I" ~ 0.5,
    x == "S" ~ 0
  )
}

antibiotics_cols <- colnames(infect_db)[c(8:ncol(infect_db))]


#Apply the case_when function to mutate every antibiotic column and sum into MDR variable
infect_db <- infect_db |>
  mutate(
    across(antibiotics_cols, 
           count_resistance)) |> 
  mutate(MDR = rowSums(across(antibiotics_cols))) |> 
  drop_na(Age, Gender, Species, Diabetes, Hypertension, Hospital_before, Infection_Freq, MDR)   #Drop all NA in the columns used to model
```

```{r}
infect_db <- infect_db |>
  mutate(
    Gender = factor(Gender),
    Species = factor(Species),
    Diabetes = factor(Diabetes),
    Hypertension = factor(Hypertension),
    Hospital_before = factor(Hospital_before)
  )
```

```{r}
model1 <- infect_db |> 
  lm(Infection_Freq ~ Age + Diabetes + Hypertension + Hospital_before,
  data = _
)
summary(model1)
```

```{r}
model2 <- infect_db |> 
  lm(Infection_Freq ~ Species,
  data = _
)
summary(model2)
```

```{r}
model3 <- infect_db |> 
  lm(Infection_Freq ~ MDR,
  data = _
)
summary(model3)
```

```{r}
model_full <- infect_db |> 
  lm(Infection_Freq ~ Species + MDR + Age + Gender + 
       Diabetes + Hypertension + Hospital_before,
  data = _
)
summary(model_full)
```

```{r}
tidy_lm <- tidy(model_full, 
     conf.int = TRUE,
     conf.level = 0.95) |> 
  mutate(term = str_replace(term, "Species", "")) |> 
  mutate(term = str_replace(term, "Yes", "")) |> 
  mutate(term = str_replace(term, "GenderM", "Gender_M")) |> 
  mutate(term = str_replace(term, "Freq1", "Freq_1")) |>
  mutate(term = str_replace(term, "Freq2", "Freq_2")) |>
  mutate(term = str_replace(term, "Freq3", "Freq_3")) |> 
  mutate(sig = factor(p.value < 0.05))
  

tidy_lm
```

```{r}
tidy_lm |>
  filter(term != "(Intercept)") |>
  mutate(term = fct_reorder(term, estimate)) |>
  ggplot(aes(y = term, x = estimate)) +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high, color = sig), height = 0.2) +
  geom_point() +
  geom_vline(xintercept = 0, linetype = "dashed") +
  labs(x = "Estimates (95% CIs)",
       y = "",
       color = "p-value < 0.05") +
  theme_minimal()
```

```{r}
tidy_lm <- tidy_lm |> 
  mutate(q.value = p.adjust(p.value),
         is_significant = case_when(q.value <= 0.05 ~ "yes",
                                    q.value > 0.05 ~ "no"))
```

```{r}
pl <- tidy_lm |>
  filter(term != "(Intercept)") |>
  ggplot(aes(x = estimate,
             y = -log10(p.value),
             colour = sig,
             label = term)) +
  geom_point(size = 1,
             alpha = 0.5) +
  geom_text_repel(size = 2.5,
                  max.overlaps = 20) +
  geom_hline(yintercept = -log10(0.05), linetype = "dotted") +
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_minimal(base_size = 16) +
  theme(
    plot.title = element_text(hjust = 1),
    plot.subtitle = element_text(hjust = 1),
    legend.position = "none") +
    labs(
    x = "Estimates",
    y = "-log10(p)")

pl
```

```{r}
library("ggrepel")
pl <- gravier_estimates |>
  mutate(lbl = case_when(
    is_significant == "yes" ~ gene,
    is_significant == "no" ~ "")) |> 
  ggplot(aes(x = estimate,
             y = -log10(p.value),
             colour = is_significant,
             label = lbl)) +
  geom_point(size = 1,
             alpha = 0.5) +
  geom_text_repel(size = 4,
                  max.overlaps = 20) +
  geom_hline(yintercept = 0) +
  theme_minimal(base_size = 16) +
  theme(
    plot.title = element_text(hjust = 1),
    plot.subtitle = element_text(hjust = 1),
    legend.position = "none") +
  labs(
    x = "Estimates",
    y = "-log10(p)",
    title = "Genes Associated with Early Metastasis in Small Node-Negative Breast Carcinoma",
    subtitle = "Genes highlighted in turquoise were significant after multiple testing correction",
    caption = "Data from DOI: 10.1002/gcc.20820")
```
